### ISSUE TITLE
Figure out a way to access jurnal.md articles.

### ISSUE THREAD

**Issue by minivan** [9-volt/radio-erevan#16]
## Unimedia

With unimedia, an article having the URL of

```
http://unimedia.info/stiri/publikatv-leanca-indeamna-autoritatile-de-la-tiraspol-sa-se-calmeze-62386.html
```

can be turned into a permalink of

```
http://unimedia.info/stiri/permalink-62386.html
```

Therefore, all the articles on unimedia are arranged consecutively.
## Publika

With Publika, a url like

```
http://www.publika.md/leanca-indeamna-autoritatile-de-la-tiraspol-la-calm--dezbaterile-din-parlament-vor-juca-un-rol-important_1460751.html
```

can be accessed through

```
http://www.publika.md/article_1460751.html
```

**important note!**

Publika articles are with a step of 10 between IDs, i.e. the next article after 1460751 will have an id of 1460761
## Task

We need to figure out something similar for Jurnal.

**Comment by bumbu** [comment]
I didn't find a way to retrieve olde news. Some unuseful workarounds.

[RSS feed gives us last 100 news](view-source:http://jurnal.md/ro/politic/rss.xml)

JurnalTV:
[Archive](http://www.jurnaltv.md/ro/arch/)
[One article info](http://www.jurnaltv.md/ro/news_block/7903013/info.html)

**Comment by bumbu** [comment]
[Here](http://bumbu.ru/fetch-articles-urls-from-google-reader/) is the solution for old articles.

Their rss feed has 100 links.
They have an average of 40 articles per day.
So we need something that will grab their rss feed once in 2 days.
